-- Question 1:
-- Find the total number of customers who have placed orders. What is the distribution of the customers across states? [4 marks]
-- Hint: For each state, count the number of customers
select count(distinct customer_id) as Total_customer from order_t;
select 
     state , count(customer_id) as customer_across_state
from 
    customer_t  group by state order by customer_across_state desc;



-- Question 2:
-- Which are the top 5 vehicle makers preferred by the customers? [4 marks]
-- Hint: For each vehicle make what is the count of the customers.
select 
p.vehicle_maker , count(o.customer_id) as Total_customer
from order_t o join product_t p on p.product_id=o.product_id 
group by p.vehicle_maker order by Total_customer desc limit 5;




-- Question 3:
-- Which is the most preferred vehicle maker in each state? [4 marks]
-- Hint: Use the window function RANK() to rank based on the count of customers for each state and vehicle maker. 
-- After ranking, take the vehicle maker whose rank is 1.

select * from (
SELECT 
	c.state,
	p.vehicle_maker,count(*) AS Total_customer,
	RANK() over (partition by state order by count(c.customer_id) desc) as ranks
FROM order_t o JOIN product_t p on p.product_id=o.product_id
INNER JOIN customer_t c on c.customer_id = o.customer_id
GROUP BY c.state,p.vehicle_maker
) preferred_vehicle
where ranks =1
order by Total_customer desc;



-- Question 4:
-- Find the overall average rating given by the customers. What is the average rating in each quarter? [5 marks]
-- Consider the following mapping for ratings:
-- “Very Bad”: 1, “Bad”: 2, “Okay”: 3, “Good”: 4, “Very Good”: 5
-- Hint: Use subquery and assign numerical values to feedback categories using a CASE statement. 
-- Then, calculate the average feedback count per quarter. Use a subquery to convert feedback 
-- into numerical values and group by quarter_number to compute the average.

select quarter_number , round(avg(customer_feedback_num),2) as average_feedback from (
select  
        quarter_number, (CASE customer_feedback
        WHEN 'Very Bad' THEN 1
        WHEN 'Bad' THEN 2
        WHEN 'Okay' THEN 3
        WHEN 'Good' THEN 4
        WHEN 'Very Good' THEN 5
    END) AS customer_feedback_num 
    FROM order_t 
 ) order_tb
 group by quarter_number order by quarter_number;
/*
3.5548
3.3550
2.9563
2.3970*/

-- Question 5:
-- Find the percentage distribution of feedback from the customers. Are customers getting more dissatisfied over time? [5 marks]
-- Hint: Calculate the percentage of each feedback type by using conditional aggregation. 
-- For each feedback category, use a CASE statement to count the occurrences and then divide by the total count of feedback for the quarter, multiplied by 100 to get the percentage. 
-- Finally, group by quarter_number and order the results to reflect the correct sequence.
-- select max(order_date), min(order_date) from order_t;

select
    quarter_number,
    (sum(CASE WHEN customer_feedback = 'Very Bad' THEN 1 ELSE 0 END) / count(customer_feedback)) * 100 AS "Very_Bad(%)",
    (sum(CASE WHEN customer_feedback = 'Bad' THEN 1 ELSE 0 END) / count(customer_feedback)) * 100 AS "Bad(%)",
    (sum(CASE WHEN customer_feedback = 'Okay' THEN 1 ELSE 0 END) / count(customer_feedback)) * 100 AS "Okay(%)",
    (sum(CASE WHEN customer_feedback = 'Good' THEN 1 ELSE 0 END) / count(customer_feedback)) * 100 AS "Good(%)",
    (sum(CASE WHEN customer_feedback = 'Very Good' THEN 1 ELSE 0 END) / count(customer_feedback)) * 100 AS "Very_Good(%)"
from order_t
group by quarter_number
order by quarter_number;


-- Question 6:
-- What is the trend of the number of orders by quarter? [3 marks]
-- Hint: count the number of orders for each quarter.
select quarter_number,count(*) as total_orders from order_t group by quarter_number order by quarter_number;





-- Question 7:
-- Calculate the net revenue generated by the company. What is the quarter-over-quarter % change in net revenue? [5 marks]
-- Hint: Net Revenue is the amount obtained by multiplying the number of units sold by the price after deducting the discounts applied.
-- Quarter over Quarter percentage change in revenue means what is the change in revenue from the subsequent quarter to the previous quarter in percentage.
-- Calculate the revenue for each quarter by summing the quantity of product and the discounted vehicle price. Use the LAG function to get the revenue from the previous quarter, and then compute the quarter-over-quarter percentage change based on the current and previous revenue values.
-- Ensure the results are ordered by quarter_number to maintain the correct sequence.
      
      
select quarter_number,
		round(total_revenue,2) AS 'Total_revenue',
        (total_revenue-LAG(total_revenue) over (order by quarter_number))/(LAG(total_revenue) over (order by quarter_number))*100 AS 'Revenue_change(%)'
      from (
      select quarter_number,
	    sum(vehicle_price*quantity*(1-discount)) AS total_revenue
      from order_t
      group by quarter_number
      ) revenue_tb;

/*# quarter_number, Total_revenue, Revenue_change(%)
'1', '39421580.16', NULL
'2', '32715830.34', '-17.010352685603'
'3', '29229896.19', '-10.655190805458'
'4', '23346779.63', '-20.127052535757'
*/
-- Question 8:
-- What is the trend of net revenue and orders by quarters? [4 marks]
-- Hint: Find out the sum of net revenue and count the number of orders for each quarter.
select quarter_number,
 round( sum(vehicle_price*quantity*(1-discount)),2)AS total_revenue,
count(*) as total_orders from order_t GROUP BY quarter_number order by quarter_number;



-- Question 9:
-- What is the average discount offered for different types of credit cards? [3 marks]
-- Hint: Find out the average of discount for each credit card type.

select credit_card_type, avg(discount) as avg_discount 
from order_t o, customer_t c where c.customer_id=o.customer_id group by credit_card_type order by avg_discount desc ;



-- Question 10:
-- What is the average time taken to ship the placed orders for each quarter? [3 marks]
-- Hint: Please use the julianday function instead of the DATEDIFF function to find the difference between the ship date and the order date.
-- The SQL Playground Editor is built on the SQLite platform, which doesn’t support the DATEDIFF function available in MySQL
select quarter_number, avg(datediff(ship_date,order_date)) as 'avg_time (days)'
from order_t group by quarter_number order by quarter_number;




/*
Total Revenue	Total Orders	Total Customers	Average Rating
<enter_value>	<enter_value>	<enter_value>	<enter_value>
Last Quarter Revenue	Last quarter Orders	Average Days to Ship	% Good Feedback
<enter_value>	<enter_value>	<enter_value>	<enter_value>

*/

-- Total Revenue
select sum(vehicle_price*quantity*(1-discount))AS total_revenue,
count(*) as total_orders from order_t; 

-- Total Orders	
select count(*) from order_t;
-- Total Customers
select count(distinct customer_id) from customer_t;

select * from order_t;

-- Average Rating
/*'1', '3.5548'
'2', '3.3550'
'3', '2.9563'
'4', '2.3970'*/

-- 3.0657

-- Last quater revenue
select sum(vehicle_price*quantity*(1-discount))AS total_revenue,
count(*) as total_orders from order_t where quarter_number=4; 

-- Average Days to Ship
select  avg(datediff(ship_date,order_date)) as avg_time 
from order_t ;

-- % Good Feedback
select count(*)/1000 from order_t where customer_feedback = 'Good';

-- 21.50%

